{
    'name': 'Delivery Management',
    'version': '17.0.3.0.0',
    'category': 'Operations/Inventory',
    'summary': 'Truck dispatch, GPS tracking, and proof-of-delivery for Odoo 17',
    'author': 'Abdelrehman Elhaj',
    'license': 'LGPL-3',
    'depends': ['base', 'sale', 'portal', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/cron.xml',
        'data/mail_template.xml',
        'views/delivery_vehicle_views.xml',
        'views/delivery_driver_views.xml',
        'views/delivery_stop_views.xml',
        'views/delivery_order_views.xml',
        'views/delivery_trip_views.xml',
        'views/create_delivery_wizard_views.xml',
        'views/sale_order_views.xml',
        'views/dashboard_action.xml',
        'views/menus.xml',
        'templates/portal_tracking.xml',
        'templates/portal_my_deliveries.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'delivery_management/static/src/css/delivery_portal.css',
            'delivery_management/static/src/js/tracking.js',
        ],
        'web.assets_backend': [
            'delivery_management/static/src/xml/dashboard.xml',
            'delivery_management/static/src/js/dashboard.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
